### ISSUE TITLE
Performance Issue with HighPsychicPylonExposure

### ISSUE THREAD

**Issue by abrenneke** [AndroidQuazar/VanillaFurnitureExpanded-Security#2]
Hi! I hope this is the right repository for VFE - Security!

I run a heavily-modded RimWorld, and I'm looking into causes for the performance not being as great as it could be. Here's a screenshot of the report for VFE - Security:

![image](https://user-images.githubusercontent.com/342540/96358601-dbf40d80-10bd-11eb-808f-2cf527ee98a6.png)

You can see that `get_HighPsychicPylonExposure` is taking up **2.9%** of the total time that I was running the game this time. I don't even have any psychic pylons on the map  (that I know about?) 😆. This 2.9% is only beaten by one other mod for total time taken, so maybe some improvements could be made!

The next three methods (`SubmersibleUtility` and `ArtilleryComp`) take up a combined **1.6%**, which is still not great, so maybe those could be improved as well!

If you think this is a red-herring, let me know!

Here is the profiling file in case you have DotTrace and want to examine it yourself: 
[nothing-selected.zip](https://github.com/AndroidQuazar/VanillaFurnitureExpanded-Security/files/5397047/nothing-selected.zip)

Cheers!

**Comment by SmashPhil** [comment]
Idk how reliable your profiler is specifically in Rimworld's case. I have noticed with a different (less official) profiler that sometimes the impact of specific methods can show up higher or lower depending on other methods on that list (which are terrible with performance). One of the big ones is IsSubmersible which you point out on the list as well. Another one is ArtilleryComp which again is also on the list. Those 2 are absolutely big impact methods and have been optimized for the next release, however looking at the method you mention in the #1 spot it doesn't appear to have anything that stands out apart from fetching a pawn's stat value. After the next release drops on steam if you still receive a hit to performance feel free to make an additional ticket, but from what myself and others have been seeing so far it's down to about a 2ms total impact now (across the board). Thanks
